language: ruby
before_install:
  - travis_retry gem install bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
  - jruby
  - rbx-2
gemfile:
  - Gemfile
  - gemfiles/redisrb-master.gemfile
matrix:
  allow_failures:
    - rvm: rbx-2
# Use the faster container based infrastructure
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false
